//===========================================================================
// 
// virus29
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Fri Jun 07 23:32:02 2019
//   Map Author: Frotty
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    string array            udg_Farbcode
    integer array           udg_Zeit
    dialog array            udg_Dialog
    unit                    udg_unhide                 = null
    button array            udg_Dialogbutton
    unit array              udg_Unit
    group array             udg_Group
    location array          udg_Pos
    integer                 udg_Spieleranzahl          = 0
    string array            udg_Spieler
    integer array           udg_SpielerRow
    multiboard array        udg_Multiboard
    rect array              udg_Pump_WP
    integer                 udg_BoneMarrows            = 0
    integer array           udg_Integer
    timer                   udg_et                     = null

    // Generated
    rect                    gg_rct_Brain               = null
    rect                    gg_rct_Mouth               = null
    rect                    gg_rct_Heart               = null
    rect                    gg_rct_Left_Lung_Part_1    = null
    rect                    gg_rct_Left_Lung_Part_2    = null
    rect                    gg_rct_Right_Lung_Part_2   = null
    rect                    gg_rct_Right_Lung_Part_1   = null
    rect                    gg_rct_Stomach             = null
    rect                    gg_rct_Stomach_Entrance    = null
    rect                    gg_rct_Visible             = null
endglobals

function InitGlobals takes nothing returns nothing
    local integer i = 0
    set i = 0
    loop
        exitwhen (i > 12)
        set udg_Farbcode[i] = ""
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 3)
        set udg_Zeit[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Dialog[i] = DialogCreate()
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 20)
        set udg_Group[i] = CreateGroup()
        set i = i + 1
    endloop

    set udg_Spieleranzahl = 0
    set i = 0
    loop
        exitwhen (i > 12)
        set udg_Spieler[i] = ""
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 12)
        set udg_SpielerRow[i] = 0
        set i = i + 1
    endloop

    set udg_BoneMarrows = 0
    set i = 0
    loop
        exitwhen (i > 6)
        set udg_Integer[i] = 0
        set i = i + 1
    endloop

    set udg_et = CreateTimer()
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h001', -3456.0, 8640.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3840.0, 7872.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3968.0, 8000.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3840.0, 8000.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3392.0, 7872.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3264.0, 7936.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3392.0, 8000.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3840.0, 7616.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3392.0, 7616.0, 270.000 )
    set u = CreateUnit( p, 'h002', -2880.0, 2560.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3456.0, 8448.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3968.0, 5888.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3840.0, -3328.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3584.0, -3072.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3456.0, 5888.0, 270.000 )
    set u = CreateUnit( p, 'h002', -4096.0, 5760.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3392.0, 5760.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3648.0, -2880.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3200.0, 8640.0, 270.000 )
    set u = CreateUnit( p, 'h004', -4032.0, -2944.0, 270.000 )
    set u = CreateUnit( p, 'h002', -2112.0, 3264.0, 270.000 )
    set u = CreateUnit( p, 'h002', -2688.0, 1856.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3072.0, 2752.0, 270.000 )
    set u = CreateUnit( p, 'h002', -4864.0, -2048.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3776.0, 2944.0, 270.000 )
    set u = CreateUnit( p, 'h002', -4800.0, 3520.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3008.0, 3712.0, 270.000 )
    set u = CreateUnit( p, 'h002', -5248.0, 1024.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3840.0, -3072.0, 270.000 )
    set u = CreateUnit( p, 'h002', -2368.0, -640.0, 270.000 )
    set u = CreateUnit( p, 'h002', -4096.0, -3264.0, 270.000 )
    set u = CreateUnit( p, 'h002', -4480.0, -1984.0, 270.000 )
    set u = CreateUnit( p, 'h002', -2880.0, 2944.0, 270.000 )
    set u = CreateUnit( p, 'h002', -2688.0, 2752.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3456.0, 8832.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3712.0, 8640.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3520.0, 3520.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3904.0, -2752.0, 270.000 )
    set u = CreateUnit( p, 'h002', -4224.0, -3072.0, 270.000 )
    set u = CreateUnit( p, 'h002', -5376.0, 2368.0, 270.000 )
    set u = CreateUnit( p, 'h00A', -2880.0, 2752.0, 270.000 )
    set u = CreateUnit( p, 'h002', -1792.0, 1600.0, 270.000 )
    set u = CreateUnit( p, 'h002', -3392.0, 576.0, 270.000 )
endfunction

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'e002', -1849.1, 8738.6, 108.350 )
endfunction

//===========================================================================
function CreateBuildingsForPlayer8 takes nothing returns nothing
    local player p = Player(8)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h000', -3392.0, 3200.0, 270.000 )
    set u = CreateUnit( p, 'h00G', -3904.0, 8256.0, 270.000 )
    set u = CreateUnit( p, 'h008', -4160.0, 8896.0, 270.000 )
endfunction

//===========================================================================
function CreateBuildingsForPlayer9 takes nothing returns nothing
    local player p = Player(9)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'h009', -2176.0, 2880.0, 270.000 )
    set u = CreateUnit( p, 'h00G', -3072.0, 8256.0, 270.000 )
    set u = CreateUnit( p, 'h008', -2752.0, 8896.0, 270.000 )
endfunction

//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n007', -1664.0, 6528.0, 270.000 )
    call WaygateSetDestination( u, GetRectCenterX(gg_rct_Stomach_Entrance), GetRectCenterY(gg_rct_Stomach_Entrance) )
    call WaygateActivate( u, true )
    set u = CreateUnit( p, 'n000', -4736.0, 7936.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, 7808.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n006', -3456.0, 9408.0, 270.000 )
    call SetUnitColor( u, ConvertPlayerColor(10) )
    set u = CreateUnit( p, 'n000', -4736.0, 6144.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2880.0, 6656.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -4736.0, 5120.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2432.0, 4288.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -6016.0, 2944.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1344.0, 2496.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1600.0, 2112.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -3392.0, 1472.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -3712.0, -704.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -4928.0, -640.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -5760.0, -5184.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -5760.0, -6720.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -6208.0, -7936.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -6400.0, -9664.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -5696.0, -10688.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -4608.0, -11072.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1408.0, -10624.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -192.0, -10816.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 704.0, -10304.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2176.0, -9920.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, -8832.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, -7680.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, -6400.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, -5184.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, -4096.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1024.0, -3072.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1408.0, -1920.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -2304.0, -1600.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1536.0, -960.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -6208.0, 2496.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -6144.0, 4672.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -7296.0, 4224.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -8192.0, 3392.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -8832.0, 2368.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -9216.0, 1216.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -9472.0, 0.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -9536.0, -1280.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -9728.0, -2432.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -9472.0, -3520.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', -1024.0, 4544.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 64.0, 4352.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 768.0, 3584.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 1536.0, 2688.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 3200.0, -2880.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 2176.0, 1856.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 2688.0, 960.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 3072.0, 0.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 3264.0, -896.0, 270.000 )
    call SetResourceAmount( u, 12500 )
    set u = CreateUnit( p, 'n000', 3328.0, -1920.0, 270.000 )
    call SetResourceAmount( u, 12500 )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0(  )
    call CreateBuildingsForPlayer8(  )
    call CreateBuildingsForPlayer9(  )
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings(  )
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_Brain = Rect( -3744.0, 8416.0, -3168.0, 8928.0 )
    set gg_rct_Mouth = Rect( -800.0, 6240.0, -448.0, 6400.0 )
    set gg_rct_Heart = Rect( -3232.0, 2432.0, -2496.0, 3200.0 )
    set gg_rct_Left_Lung_Part_1 = Rect( -5280.0, 1184.0, -4192.0, 3232.0 )
    set gg_rct_Left_Lung_Part_2 = Rect( -4864.0, 96.0, -3712.0, 1184.0 )
    set gg_rct_Right_Lung_Part_2 = Rect( -2592.0, -576.0, -1728.0, 1536.0 )
    set gg_rct_Right_Lung_Part_1 = Rect( -3008.0, -288.0, -2176.0, 1216.0 )
    set gg_rct_Stomach = Rect( -4416.0, -3424.0, -3488.0, -2656.0 )
    set gg_rct_Stomach_Entrance = Rect( -3488.0, -3904.0, -3072.0, -3488.0 )
    set gg_rct_Visible = Rect( -1984.0, 6240.0, -416.0, 6816.0 )
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************
//TESH.scrollpos=0
//TESH.alwaysfold=0

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_COMPUTER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(1), false )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(2), false )
    call SetPlayerController( Player(2), MAP_CONTROL_USER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(3), false )
    call SetPlayerController( Player(3), MAP_CONTROL_USER )

    // Player 4
    call SetPlayerStartLocation( Player(4), 4 )
    call SetPlayerColor( Player(4), ConvertPlayerColor(4) )
    call SetPlayerRacePreference( Player(4), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(4), false )
    call SetPlayerController( Player(4), MAP_CONTROL_USER )

    // Player 5
    call SetPlayerStartLocation( Player(5), 5 )
    call SetPlayerColor( Player(5), ConvertPlayerColor(5) )
    call SetPlayerRacePreference( Player(5), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(5), false )
    call SetPlayerController( Player(5), MAP_CONTROL_USER )

    // Player 6
    call SetPlayerStartLocation( Player(6), 6 )
    call SetPlayerColor( Player(6), ConvertPlayerColor(6) )
    call SetPlayerRacePreference( Player(6), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(6), false )
    call SetPlayerController( Player(6), MAP_CONTROL_USER )

    // Player 7
    call SetPlayerStartLocation( Player(7), 7 )
    call SetPlayerColor( Player(7), ConvertPlayerColor(7) )
    call SetPlayerRacePreference( Player(7), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(7), false )
    call SetPlayerController( Player(7), MAP_CONTROL_USER )

    // Player 8
    call SetPlayerStartLocation( Player(8), 8 )
    call ForcePlayerStartLocation( Player(8), 8 )
    call SetPlayerColor( Player(8), ConvertPlayerColor(8) )
    call SetPlayerRacePreference( Player(8), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(8), false )
    call SetPlayerController( Player(8), MAP_CONTROL_USER )

    // Player 9
    call SetPlayerStartLocation( Player(9), 9 )
    call ForcePlayerStartLocation( Player(9), 9 )
    call SetPlayerColor( Player(9), ConvertPlayerColor(9) )
    call SetPlayerRacePreference( Player(9), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(9), false )
    call SetPlayerController( Player(9), MAP_CONTROL_USER )

    // Player 11
    call SetPlayerStartLocation( Player(11), 10 )
    call ForcePlayerStartLocation( Player(11), 10 )
    call SetPlayerColor( Player(11), ConvertPlayerColor(11) )
    call SetPlayerRacePreference( Player(11), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(11), false )
    call SetPlayerController( Player(11), MAP_CONTROL_COMPUTER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_1208
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerState( Player(0), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(8), 0 )
    call SetPlayerState( Player(8), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(9), 0 )
    call SetPlayerState( Player(9), PLAYER_STATE_ALLIED_VICTORY, 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(8), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(8), true )

    // Force: TRIGSTR_1204
    call SetPlayerTeam( Player(1), 1 )
    call SetPlayerState( Player(1), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(2), 1 )
    call SetPlayerState( Player(2), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(3), 1 )
    call SetPlayerState( Player(3), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(4), 1 )
    call SetPlayerState( Player(4), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(5), 1 )
    call SetPlayerState( Player(5), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(6), 1 )
    call SetPlayerState( Player(6), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(7), 1 )
    call SetPlayerState( Player(7), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(11), 1 )
    call SetPlayerState( Player(11), PLAYER_STATE_ALLIED_VICTORY, 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(7), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(7), true )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 1, 3 )
    call SetStartLocPrio( 1, 0, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 1, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 1, 2, 5, MAP_LOC_PRIO_LOW )

    call SetStartLocPrioCount( 2, 4 )
    call SetStartLocPrio( 2, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 1, 7, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 2, 2, 8, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 3, 9, MAP_LOC_PRIO_LOW )

    call SetStartLocPrioCount( 3, 2 )
    call SetStartLocPrio( 3, 0, 4, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 1, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 4, 2 )
    call SetStartLocPrio( 4, 0, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 1, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 5, 2 )
    call SetStartLocPrio( 5, 0, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 5, 1, 4, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 6, 2 )
    call SetStartLocPrio( 6, 0, 5, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 6, 1, 7, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 7, 1 )
    call SetStartLocPrio( 7, 0, 6, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 8, 1 )
    call SetStartLocPrio( 8, 0, 9, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 9, 1 )
    call SetStartLocPrio( 9, 0, 8, MAP_LOC_PRIO_HIGH )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    local weathereffect we
    call SetCameraBounds( -11520.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -11776.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 7424.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 11264.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -11520.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 11264.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 7424.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -11776.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCFelwood\\DNCFelwoodTerrain\\DNCFelwoodTerrain.mdl", "Environment\\DNC\\DNCFelwood\\DNCFelwoodUnit\\DNCFelwoodUnit.mdl" )
    call SetTerrainFogEx( 0, 500.0, 4000.0, 0.400, 0.451, 0.000, 0.000 )
    call SetWaterBaseColor( 45, 0, 0, 255 )
    set we = AddWeatherEffect( Rect(-12288.0,-12288.0,8192.0,12288.0), 'FDrl' )
    call EnableWeatherEffect( we, true )
    call NewSoundEnvironment( "psychotic" )
    call SetAmbientDaySound( "FelwoodDay" )
    call SetAmbientNightSound( "FelwoodNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateRegions(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_001" )
    call SetMapDescription( "TRIGSTR_003" )
    call SetPlayers( 11 )
    call SetTeams( 11 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, -2880.0, 2752.0 )
    call DefineStartLocation( 1, -9024.0, -3008.0 )
    call DefineStartLocation( 2, -7680.0, 2816.0 )
    call DefineStartLocation( 3, -4608.0, -10240.0 )
    call DefineStartLocation( 4, -256.0, -10048.0 )
    call DefineStartLocation( 5, -1408.0, -6400.0 )
    call DefineStartLocation( 6, 2496.0, -2048.0 )
    call DefineStartLocation( 7, 960.0, 2112.0 )
    call DefineStartLocation( 8, -4032.0, 8768.0 )
    call DefineStartLocation( 9, -2944.0, 8768.0 )
    call DefineStartLocation( 10, -3392.0, -3648.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call InitCustomTeams(  )
    call InitAllyPriorities(  )
endfunction

